### ISSUE TITLE
Support for Thunderbird 124?

### ISSUE THREAD

**Issue by ma-sadeghi** [eyalroz/bidimailui#120]
Hi, 
Let me first thank you for creating this life-saving extension! I was wondering if you'd make a new release for compatibility with the latest Thunderbird (v124). Thanks!

**Comment by MehdiChinoune** [comment]
124 is a beta release.
Could you support the latest v128.

**Comment by eyalroz** [comment]
Working on this right now. Try this build:

[bidimailui_0.15.0b1_tbird.xpi.zip](https://github.com/user-attachments/files/16400842/bidimailui_0.15.0b1_tbird.xpi.zip)

**Comment by MehdiChinoune** [comment]
> Working on this right now. Try this build:
> 
> [bidimailui_0.15.0b1_tbird.xpi.zip](https://github.com/user-attachments/files/16400842/bidimailui_0.15.0b1_tbird.xpi.zip)

- The direction of writing doesn't show up.
- Choosing language of writing in the bottom doesn't show up.

**Comment by eyalroz** [comment]
Done and released.

**Comment by ma-sadeghi** [comment]
Thank you :)

**Comment by eyalroz** [comment]
The best way to thank me right now is to put pressure on the government where you live (Canada, right) to in turn put pressure on Israel to end its murderous campaign in Gaza... which is what I've been busy with instead of updating BiDiMail UI.

Plus: https://donate.unrwa.org/gaza/ , or any other relevant organizations...
