### ISSUE TITLE
Strange text encoding behavior while viewing emails in TB68 & TB78

### ISSUE THREAD

**Issue by KIAOman2020** [eyalroz/bidimailui#28]
I'm using BiDimailui 0.10.1 with TB 68.10 & BiDimailui 0.11b2 with TB 78.1.1 and I notice strange behavior with text encoding while viewing emails specifically (unicode, Arabic Windows & western text encoding), where RTL & LTR text are not aligned correctly.
Find pic sample.
![BiDi text encoding issue](https://user-images.githubusercontent.com/68848728/90241917-1252a980-de3d-11ea-939d-1a25b7d2bed5.png)
.
This issue is only with view email, but if I reply, forward, compose email, alignment will be fine!

**Comment by eyalroz** [comment]
Please do one of the following:

1. Save the message to an .eml file and attach it here or email it to me
2. Put the message in a folder of its own; determine its location on disk; compress it and post it here or email it to me.

That way I can have a closer look.

**Comment by eyalroz** [comment]
Also, the code and logic applied when editing/composing is different from what's done when displaying, so it's not surprising you experience different behavior.

**Comment by KIAOman2020** [comment]
Hi Eyal,

I have sent you sample mail.

**Comment by eyalroz** [comment]
The behavior you see is valid, as is due to specific features of your message. You see, this message has several "block elements" (like DIV and P) with specific direction settings! e.g. `<p dir="rtl">`. That forces the direction.

Now, what bidimailui does is very _gently_ nudge the directions, exactly so as not to override any settings the document itself has. So when forcing RTL or LTR direction, I set the direction style of the body element - and that style trickles down... only while it is not interrupted by local settings. It's a similar situation with autodetection, except there, each block element has its own markings that I give it, depending on whether it has LTR, RTL or mixed content; but the translation of that into the actual direction of layout  does not override the settings on specific elements.
