### ISSUE TITLE
Update maximum version for 115 support

### ISSUE THREAD

**Issue by eyalroz** [eyalroz/bidimailui#74]
TB v115 needs to see the maximum version be at least 115.* to use the extension... let's update this field then.

**Comment by MadMattAu** [comment]
When might this appear on ATN?

**Comment by eyalroz** [comment]
@MadMattAu : The update is on the development branch, where I'm working on v115 support. When it's done, or rather, when it's half-done at least to the level of publishing a beta, it will go on ATN.

**Comment by MadMattAu** [comment]
I am just trying to get a clue as to when that might be.  I am starting to see folk on SUMO lamenting the absence of a 115 version post update.  I would much prefer to tell them that you expect to have something this week, next week, or hopefully this month or whatever. Based on what you think. Otherwise, all I can do if refer them to your support link. Something I think would be counterproductive really.

**Comment by eyalroz** [comment]
Please try out [the new beta](https://github.com/eyalroz/bidimailui/releases/tag/v0.14.0-b1) and open a new issue if you experience any problems.
